version: "3.8"


services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - ./.env
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    depends_on:
      - db
    container_name: web
    env_file:
      - ./.env
    volumes:
      - ./data/static/:/app/data/static/
    command: sh -c "./manage.py collectstatic --no-input &&
                    ./manage.py migrate &&
                    ./manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./data/nginx/nginx.conf/:/etc/nginx/conf.d/default.conf/
      - ./data/static/:/app/data/static/
    ports:
      - "80:80"

volumes:
  postgres_data: