version: "3.8"


services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - ./.env
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    restart: always
    container_name: redis

  celery:
    build: .
    container_name: celery
    command: celery -A Hacker_News worker -l info
    volumes:
      - ./:/app/
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A Hacker_News beat -l info
    volumes:
      - ./:/app/
    depends_on:
      - redis

  web:
    build: .
    depends_on:
      - db
      - redis
    container_name: web
    env_file:
      - ./.env
    volumes:
      - .:/app/
      - ./data/static/:/app/data/static/
    command: sh -c "./manage.py collectstatic --no-input &&
                    ./manage.py migrate &&
                    gunicorn -b 0.0.0.0:8000 Hacker_News.wsgi --reload"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./data/nginx/nginx.conf/:/etc/nginx/conf.d/default.conf/
      - ./data/static/:/app/data/static/
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data: